include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - file_names
    - prefer_single_quotes
    - sort_constructors_first
    - directives_ordering

analyzer:
  errors:
    invalid_annotation_target: ignore
